// This file is auto-generated by scripts/generate-articles-content.mjs.
// Do not edit manually.

export const featuredArticleId = "om-chiffres-stade";

export const articles = [
  {
    "id": "cantines-prix-qualite-quartiers",
    "title": "Cantines marseillaises : pourquoi la facture grimpe plus vite que la qualité",
    "excerpt": "Pendant six semaines, Mistral a comparé menus affichés, portions servies et prix facturés dans plusieurs secteurs de Marseille. Le constat est net : les écarts entre quartiers se creusent, alors que les familles paient de plus en plus.",
    "caption": "Service du midi dans une école du 3e arrondissement, relevé de terrain Mistral.",
    "image": "https://images.unsplash.com/photo-1544378730-8b5104b18790?auto=format&fit=crop&w=1400&q=80",
    "date": "2026-03-17",
    "updatedDate": "2026-03-17",
    "author": "Nassim Belkacem",
    "readTimeMinutes": 11,
    "sections": [
      {
        "title": "Ce que montrent les relevés de terrain",
        "paragraphs": [
          "Entre le 29 janvier et le 11 mars 2026, nous avons observé 18 services de cantine dans six groupes scolaires situés dans les 2e, 3e, 8e, 11e et 14e arrondissements. Dans chaque établissement, nous avons comparé les menus annoncés la semaine précédente aux plats effectivement servis et aux portions réellement distribuées.",
          "Sur 18 services observés, 11 présentaient au moins une différence significative entre le menu affiché et le plateau final : absence d'accompagnement prévu, remplacement d'un produit frais par un produit surgelé, ou réduction de la portion protéinée en fin de service. Ces écarts apparaissent davantage dans les écoles où la fréquentation dépasse les capacités théoriques de la cuisine de liaison.",
          "Les familles rencontrées décrivent surtout une perte de confiance : elles ne contestent pas seulement la hausse tarifaire, elles disent ne plus comprendre ce qu'elles financent. Dans deux écoles du nord de la ville, plusieurs parents nous ont montré des tickets de paiement mensuel supérieurs à ceux de 2024, alors que leurs enfants signalent des repas moins variés."
        ]
      },
      {
        "title": "Des hausses qui pèsent davantage selon les quartiers",
        "paragraphs": [
          "La grille municipale reste progressive, mais ses effets concrets sont inégaux. Dans les quartiers où les revenus fluctuent et où les dossiers administratifs sont plus souvent incomplets, les bascules vers des tranches supérieures sont plus fréquentes. Résultat : certaines familles passent d'un palier social à un palier intermédiaire sans avoir réellement gagné en pouvoir d'achat.",
          "Nos entretiens avec des directeurs d'école confirment un phénomène régulier : les changements de tranche sont compris tardivement, parfois plusieurs mois après la rentrée, lorsque les régularisations tombent. Dans ce contexte, une hausse de quelques dizaines d'euros mensuels devient un choc budgétaire pour des foyers déjà contraints.",
          "Ce décalage est peu visible dans les communications institutionnelles, qui raisonnent en moyenne annuelle. Or, sur le terrain, les ménages comparent leur fin de mois, pas des moyennes consolidées."
        ]
      },
      {
        "title": "Le nerf du sujet : marchés, indexation et contrôle",
        "paragraphs": [
          "Les documents contractuels que nous avons examinés montrent une logique d'indexation automatique des coûts (énergie, transport, matières premières) qui protège d'abord la continuité du service. Cette mécanique est compréhensible, mais elle rend la facture finale très sensible aux aléas économiques, avec un contrôle qualitatif qui reste plus lent que la hausse des coûts.",
          "Plusieurs agents de restauration évoquent un pilotage \"à flux tendu\" : ajustements de dernière minute, substitutions en cas de rupture, et arbitrages opérés au plus près de la production. Ce fonctionnement limite les ruptures de service, mais il dégrade la stabilité des menus et la lisibilité pour les familles.",
          "Le principal angle mort reste la publication de données de suivi compréhensibles par le public. Les tableaux administratifs existent, mais ils ne permettent pas toujours de relier clairement prix payé, prestation promise et prestation servie, école par école."
        ]
      },
      {
        "title": "Ce que répond la mairie",
        "paragraphs": [
          "La municipalité souligne que l'inflation alimentaire et énergétique a imposé des ajustements successifs pour maintenir l'offre de restauration. Elle affirme également avoir renforcé les clauses de qualité dans les marchés récents, en particulier sur la traçabilité et la part de produits durables.",
          "Sur les écarts de service signalés dans certains établissements, la ville reconnaît des tensions ponctuelles liées au volume de repas, aux absences de personnel et aux retards logistiques. Elle indique avoir lancé des audits ciblés dans les secteurs les plus en difficulté et promet une publication plus régulière des indicateurs de suivi.",
          "Reste une question centrale : à quel rythme ces améliorations seront-elles perceptibles pour les familles qui subissent déjà la hausse des factures depuis plusieurs trimestres."
        ]
      },
      {
        "title": "Parents et agents demandent la même chose : visibilité",
        "paragraphs": [
          "Les collectifs de parents interrogés ne réclament pas uniquement une baisse générale des tarifs. Leur priorité est la prévisibilité : savoir à l'avance combien coûtera le mois suivant, comprendre précisément pourquoi une tranche change, et disposer d'un canal de recours simple en cas d'erreur.",
          "Du côté des équipes de terrain, la demande rejoint celle des familles : plus de transparence opérationnelle. Les agents souhaitent des plannings stabilisés, des marges de sécurité sur les stocks sensibles et des protocoles clairs lorsque les menus doivent être modifiés.",
          "Ces deux attentes convergent vers un même besoin démocratique : sortir d'une logique de correction après coup, et installer un suivi public continu de la qualité et du prix."
        ]
      },
      {
        "title": "Ce qu'il faut surveiller d'ici l'été",
        "paragraphs": [
          "Trois indicateurs seront décisifs dans les prochains mois : l'évolution des tranches tarifaires réellement appliquées, le taux de menus effectivement conformes, et le délai moyen de traitement des réclamations familles. Sans ces données, le débat restera bloqué entre ressenti individuel et communication globale.",
          "La prochaine séquence budgétaire municipale offrira un test concret : soit la ville détaille un plan de stabilisation lisible, soit la hausse continuera d'être absorbée au cas par cas par les ménages et les établissements.",
          "Pour les parents comme pour les agents, la question n'est plus de savoir si le service est indispensable, mais s'il peut rester soutenable financièrement tout en étant cohérent avec les promesses de qualité affichées."
        ]
      }
    ],
    "sources": [
      {
        "label": "Subventions associations Marseille 2024",
        "file": "subventions-associations-marseille-2024.csv",
        "type": "Jeu de données (CSV)",
        "date": "2026-03-15",
        "context": "Croisé avec les dépenses connexes de restauration scolaire pour analyser les arbitrages budgétaires locaux."
      },
      {
        "label": "Arrêté municipal circulation Vieux-Port 2024",
        "file": "arrete-circulation-vieux-port-2024.txt",
        "type": "Arrêté municipal",
        "date": "2026-03-14",
        "context": "Référence utilisée pour vérifier les contraintes logistiques et d'acheminement évoquées par les agents."
      },
      {
        "label": "Convention d'occupation Vélodrome - avenant 2",
        "file": "convention-velodrome-avenant-2.txt",
        "type": "Convention publique",
        "date": "2026-03-13",
        "context": "Document de comparaison utilisé pour relire les clauses d'indexation contractuelle et les mécanismes de suivi."
      }
    ],
    "tags": [
      "Économie",
      "Quartiers",
      "Politique"
    ]
  },
  {
    "id": "om-chiffres-stade",
    "title": "OM : Les chiffres cachés du nouveau stade",
    "excerpt": "Notre enquête révèle les montants réels du partenariat public-privé pour le Vélodrome. Un dossier qui bouscule les certitudes municipales.",
    "caption": "Jean-Pierre C., adjoint aux finances, devant l'Hôtel de Ville. Juin 2024.",
    "image": "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1600&q=80",
    "date": "2026-03-11",
    "updatedDate": "2026-03-12",
    "author": "Léa Martin",
    "readTimeMinutes": 8,
    "sources": [
      {
        "label": "Convention d'occupation Vélodrome - avenant 2",
        "file": "convention-velodrome-avenant-2.txt",
        "type": "Convention publique",
        "date": "2026-03-10",
        "context": "Utilisée pour vérifier les clauses financières et les obligations de la collectivité."
      },
      {
        "label": "Subventions associations Marseille 2024",
        "file": "subventions-associations-marseille-2024.csv",
        "type": "Jeu de données (CSV)",
        "date": "2026-03-09",
        "context": "Croisée avec les montants annoncés pour reconstituer les lignes budgétaires citées."
      }
    ],
    "corrections": [
      {
        "date": "2026-03-13",
        "detail": "Correction d'une précision sur l'échéancier de versement, sans impact sur la conclusion de l'enquête."
      }
    ],
    "tags": [
      "Politique",
      "Économie",
      "Urbanisme"
    ]
  },
  {
    "id": "dockers-port-autonome",
    "title": "Les dockers racontent l'autre visage du port autonome",
    "excerpt": "Entre automatisation et fatigue chronique, les travailleurs décrivent une réorganisation qui avance plus vite que la concertation.",
    "caption": "Hangar J1, entretien croisé mené sur trois semaines.",
    "image": "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=900&q=80",
    "date": "2026-03-09",
    "updatedDate": "2026-03-09",
    "author": "Nassim Belkacem",
    "readTimeMinutes": 6,
    "tags": [
      "Économie",
      "Quartiers"
    ]
  },
  {
    "id": "retards-nord-ville",
    "title": "Transports : les retards se concentrent dans le nord de la ville",
    "excerpt": "Nos relevés montrent une fracture persistante entre promesses de réseau et réalité des temps de trajet.",
    "caption": "Analyse à partir d'horaires publics et de témoignages d'usagers.",
    "image": "https://images.unsplash.com/photo-1470004914212-05527e49370b?auto=format&fit=crop&w=900&q=80",
    "date": "2026-03-06",
    "updatedDate": "2026-03-08",
    "author": "Sarah Cadi",
    "readTimeMinutes": 7,
    "tags": [
      "Mobilités",
      "Quartiers"
    ]
  },
  {
    "id": "mediterranee-argument-politique",
    "title": "La Méditerranée comme argument politique permanent",
    "excerpt": "Quand les élus invoquent l'exception marseillaise, que disent vraiment les arbitrages budgétaires ?",
    "caption": "Chronique signée rédaction Mistral.",
    "image": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80",
    "date": "2026-03-03",
    "updatedDate": "2026-03-05",
    "author": "Paul Ferrand",
    "readTimeMinutes": 5,
    "tags": [
      "Politique",
      "Culture"
    ]
  },
  {
    "id": "ecoles-renovees-marches",
    "title": "Écoles rénovées : les marchés publics passés au crible",
    "excerpt": "Un relevé ligne par ligne des appels d'offres fait ressortir des écarts de coûts non expliqués.",
    "caption": "Documents consolidés sur douze établissements.",
    "image": "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=900&q=80",
    "date": "2026-02-26",
    "updatedDate": "2026-03-01",
    "author": "Amel Chabane",
    "readTimeMinutes": 9,
    "sources": [
      {
        "label": "Subventions associations Marseille 2024",
        "file": "subventions-associations-marseille-2024.csv",
        "type": "Jeu de données (CSV)",
        "date": "2026-02-27",
        "context": "Permet de contrôler les écarts entre montants votés et montants effectivement versés."
      }
    ],
    "tags": [
      "Urbanisme",
      "Économie"
    ]
  },
  {
    "id": "arretes-municipaux-riverains",
    "title": "Les arrêtés municipaux réclamés par les riverains",
    "excerpt": "Mistral publie les textes complets pour suivre ce qui a réellement été décidé autour des grands chantiers.",
    "caption": "Téléchargements disponibles dans l'espace documents.",
    "image": "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=900&q=80",
    "date": "2026-02-21",
    "updatedDate": "2026-02-22",
    "author": "Léa Martin",
    "readTimeMinutes": 6,
    "sources": [
      {
        "label": "Arrêté municipal circulation Vieux-Port 2024",
        "file": "arrete-circulation-vieux-port-2024.txt",
        "type": "Arrêté municipal",
        "date": "2026-02-20",
        "context": "Texte de référence cité pour vérifier les décisions réellement applicables sur le terrain."
      }
    ],
    "tags": [
      "Urbanisme",
      "Politique"
    ]
  },
  {
    "id": "memoire-belle-de-mai",
    "title": "À la Belle de Mai, une mémoire de quartier s'organise",
    "excerpt": "Carnets, affiches et photos de façade composent une archive citoyenne face au récit officiel.",
    "caption": "Rencontre dans un ancien atelier partagé.",
    "image": "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=900&q=80",
    "date": "2026-02-16",
    "updatedDate": "2026-02-17",
    "author": "Yanis Gherbi",
    "readTimeMinutes": 5,
    "tags": [
      "Culture",
      "Quartiers"
    ]
  },
  {
    "id": "tramway-est-hypotheses",
    "title": "Extension du tramway à l'est : les hypothèses sur la table",
    "excerpt": "Trois scénarios de tracé sont analysés avec leurs impacts budgétaires et leurs effets sur la desserte locale.",
    "caption": "Simulation à partir des dernières délibérations publiques.",
    "image": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=900&q=80",
    "date": "2026-02-11",
    "updatedDate": "2026-02-14",
    "author": "Sarah Cadi",
    "readTimeMinutes": 8,
    "tags": [
      "Mobilités",
      "Urbanisme",
      "Économie"
    ]
  },
  {
    "id": "friches-culturelles-sud",
    "title": "Friches culturelles du sud : qui décide des occupations ?",
    "excerpt": "Derrière les projets temporaires, des arbitrages politiques tranchent entre programmation artistique et rentabilité.",
    "caption": "Entretiens croisés avec collectifs, mairie et exploitants.",
    "image": "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=900&q=80",
    "date": "2026-02-07",
    "updatedDate": "2026-02-10",
    "author": "Paul Ferrand",
    "readTimeMinutes": 7,
    "tags": [
      "Culture",
      "Politique",
      "Quartiers"
    ]
  }
];
