// This file is auto-generated by scripts/generate-articles-content.mjs.
// Do not edit manually.

export const featuredArticleId = "om-chiffres-stade";

export const authors = [
  {
    "id": "amel-chabane",
    "name": "Amel Chabane",
    "role": "Journaliste data",
    "bio": "Spécialiste des marchés publics, budgets et jeux de données municipaux.",
    "avatar": "https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?auto=format&fit=crop&w=320&q=80",
    "email": "amel.chabane@mistral-media.fr"
  },
  {
    "id": "lea-martin",
    "name": "Léa Martin",
    "role": "Rédactrice enquêtes",
    "bio": "Suit les sujets de politiques publiques et de finances locales à Marseille.",
    "avatar": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80",
    "email": "lea.martin@mistral-media.fr"
  },
  {
    "id": "nassim-belkacem",
    "name": "Nassim Belkacem",
    "role": "Journaliste terrain",
    "bio": "Documente les services publics et les dynamiques sociales dans les quartiers marseillais.",
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=320&q=80",
    "email": "nassim.belkacem@mistral-media.fr"
  },
  {
    "id": "paul-ferrand",
    "name": "Paul Ferrand",
    "role": "Chroniqueur politique",
    "bio": "Décrypte les arbitrages politiques et leur impact concret pour les habitants.",
    "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80",
    "email": "paul.ferrand@mistral-media.fr"
  },
  {
    "id": "philou",
    "name": "Philou",
    "role": "Contributeur",
    "bio": "Auteur test pour la validation du workflow éditorial Decap Bridge.",
    "avatar": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=320&q=80",
    "email": "philou@mistral-media.fr"
  },
  {
    "id": "sarah-cadi",
    "name": "Sarah Cadi",
    "role": "Journaliste mobilités",
    "bio": "Analyse les transports, l’accès aux services et les inégalités de desserte.",
    "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=320&q=80",
    "email": "sarah.cadi@mistral-media.fr"
  },
  {
    "id": "yanis-gherbi",
    "name": "Yanis Gherbi",
    "role": "Reporter culture et quartiers",
    "bio": "Raconte les initiatives locales, la mémoire urbaine et les collectifs citoyens.",
    "avatar": "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?auto=format&fit=crop&w=320&q=80",
    "email": "yanis.gherbi@mistral-media.fr"
  }
];

export const series = [
  {
    "id": "finances-publiques-marseille",
    "title": "Finances publiques marseillaises",
    "description": "Suivi des budgets, marchés publics et choix d’allocation des moyens à Marseille.",
    "coverImage": "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "id": "ville-et-quartiers",
    "title": "Ville et quartiers",
    "description": "Une série d’articles sur les écarts de services, de mobilités et de cadre de vie selon les secteurs.",
    "coverImage": "https://images.unsplash.com/photo-1527631746610-bca00a040d60?auto=format&fit=crop&w=1200&q=80"
  }
];

export const documents = [
  {
    "id": "arrete-circulation-vieux-port-2024",
    "title": "Arrêté municipal circulation Vieux-Port 2024",
    "file": "arrete-circulation-vieux-port-2024.txt",
    "type": "Arrêté municipal",
    "date": "2026-03-14",
    "sourceUrl": ""
  },
  {
    "id": "convention-velodrome-avenant-2",
    "title": "Convention d'occupation Vélodrome - avenant 2",
    "file": "convention-velodrome-avenant-2.txt",
    "type": "Convention publique",
    "date": "2026-03-10",
    "sourceUrl": ""
  },
  {
    "id": "subventions-associations-marseille-2024",
    "title": "Subventions associations Marseille 2024",
    "file": "subventions-associations-marseille-2024.csv",
    "type": "Jeu de données (CSV)",
    "date": "2026-03-09",
    "sourceUrl": ""
  }
];

export const articles = [
  {
    "id": "om-chiffres-stade",
    "title": "OM : Les chiffres cachés du nouveau stade",
    "excerpt": "Notre enquête révèle les montants réels du partenariat public-privé pour le Vélodrome. Un dossier qui bouscule les certitudes municipales.",
    "caption": "Jean-Pierre C., adjoint aux finances, devant l'Hôtel de Ville. Juin 2024.",
    "image": "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1600&q=80",
    "date": "2026-03-11",
    "updatedDate": "2026-03-12",
    "author": "Léa Martin",
    "readTimeMinutes": 8,
    "sources": [
      {
        "label": "Convention d'occupation Vélodrome - avenant 2",
        "file": "convention-velodrome-avenant-2.txt",
        "type": "Convention publique",
        "date": "2026-03-10",
        "context": "Utilisée pour vérifier les clauses financières et les obligations de la collectivité."
      },
      {
        "label": "Subventions associations Marseille 2024",
        "file": "subventions-associations-marseille-2024.csv",
        "type": "Jeu de données (CSV)",
        "date": "2026-03-09",
        "context": "Croisée avec les montants annoncés pour reconstituer les lignes budgétaires citées."
      }
    ],
    "corrections": [
      {
        "date": "2026-03-13",
        "detail": "Correction d'une précision sur l'échéancier de versement, sans impact sur la conclusion de l'enquête."
      }
    ],
    "tags": [
      "Politique",
      "Économie",
      "Urbanisme"
    ],
    "editorialTemplate": "enquete",
    "status": "published",
    "publishAt": "2026-03-11T06:00:00.000Z",
    "seoTitle": "OM : Les chiffres cachés du nouveau stade",
    "socialTitle": "OM stade: les chiffres clés",
    "seoDescription": "Notre enquête révèle les montants réels du partenariat public-privé pour le Vélodrome. Un dossier qui bouscule les certitudes municipales.",
    "ogImage": "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1600&q=80",
    "redirectFrom": [
      "om-velodrome-chiffres-caches"
    ],
    "factCheckedBy": "Léa Martin",
    "legalReviewedBy": "Léa Martin",
    "sensitiveTopic": false,
    "heroImageAlt": "OM : Les chiffres cachés du nouveau stade",
    "imageCredit": "Photo: Unsplash",
    "location": "Marseille",
    "series": "finances-publiques-marseille",
    "relatedArticles": [
      "arretes-municipaux-riverains",
      "cantines-prix-qualite-quartiers",
      "dockers-port-autonome"
    ],
    "sourceLinks": [],
    "dataHighlights": [
      {
        "title": "Répartition des montants engagés",
        "type": "bar",
        "unit": "M€",
        "note": "Montants consolidés à partir des avenants et documents budgétaires cités dans les sources.",
        "items": [
          {
            "label": "Travaux initiaux",
            "value": 42
          },
          {
            "label": "Maintenance",
            "value": 17
          },
          {
            "label": "Compensations",
            "value": 9
          }
        ]
      },
      {
        "title": "Chronologie des décisions",
        "type": "timeline",
        "items": [
          {
            "label": "Vote de l'avenant",
            "date": "2024-09",
            "detail": "Le conseil municipal valide la nouvelle trajectoire financière."
          },
          {
            "label": "Mise à jour des lignes budgétaires",
            "date": "2025-04",
            "detail": "Les engagements apparaissent dans le budget primitif."
          },
          {
            "label": "Publication de l'enquête",
            "date": "2026-03",
            "detail": "Mistral recoupe contrats, délibérations et flux financiers."
          }
        ]
      },
      {
        "title": "Écart entre annoncé et constaté",
        "type": "comparison",
        "unit": "M€",
        "items": [
          {
            "label": "Coût global",
            "value": 68,
            "valueSecondary": 74,
            "detail": "Annonce publique vs total reconstitué documents en main."
          }
        ]
      }
    ],
    "authorId": "lea-martin",
    "factCheckedById": "lea-martin",
    "legalReviewedById": "lea-martin",
    "sections": []
  },
  {
    "id": "dockers-port-autonome",
    "title": "Les dockers racontent l'autre visage du port autonome",
    "excerpt": "Entre automatisation et fatigue chronique, les travailleurs décrivent une réorganisation qui avance plus vite que la concertation.",
    "caption": "Hangar J1, entretien croisé mené sur trois semaines.",
    "image": "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=900&q=80",
    "date": "2026-03-09",
    "updatedDate": "2026-03-09",
    "author": "Nassim Belkacem",
    "readTimeMinutes": 6,
    "tags": [
      "Économie",
      "Quartiers"
    ],
    "editorialTemplate": "decryptage",
    "status": "published",
    "publishAt": "2026-03-09T06:00:00.000Z",
    "seoTitle": "Les dockers racontent l'autre visage du port autonome",
    "seoDescription": "Entre automatisation et fatigue chronique, les travailleurs décrivent une réorganisation qui avance plus vite que la concertation.",
    "ogImage": "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=900&q=80",
    "factCheckedBy": "Nassim Belkacem",
    "sensitiveTopic": false,
    "heroImageAlt": "Les dockers racontent l'autre visage du port autonome",
    "imageCredit": "Photo: Unsplash",
    "location": "Marseille",
    "series": "finances-publiques-marseille",
    "relatedArticles": [
      "arretes-municipaux-riverains",
      "cantines-prix-qualite-quartiers",
      "ecoles-renovees-marches"
    ],
    "sourceLinks": [],
    "authorId": "nassim-belkacem",
    "factCheckedById": "nassim-belkacem",
    "sections": [],
    "sources": [],
    "corrections": [],
    "redirectFrom": [],
    "dataHighlights": []
  },
  {
    "id": "retards-nord-ville",
    "title": "Transports : les retards se concentrent dans le nord de la ville",
    "excerpt": "Nos relevés montrent une fracture persistante entre promesses de réseau et réalité des temps de trajet.",
    "caption": "Analyse à partir d'horaires publics et de témoignages d'usagers.",
    "image": "https://images.unsplash.com/photo-1470004914212-05527e49370b?auto=format&fit=crop&w=900&q=80",
    "date": "2026-03-06",
    "updatedDate": "2026-03-08",
    "author": "Sarah Cadi",
    "readTimeMinutes": 7,
    "tags": [
      "Mobilités",
      "Quartiers"
    ],
    "editorialTemplate": "decryptage",
    "status": "published",
    "publishAt": "2026-03-06T06:00:00.000Z",
    "seoTitle": "Transports : les retards se concentrent dans le nord de la ville",
    "seoDescription": "Nos relevés montrent une fracture persistante entre promesses de réseau et réalité des temps de trajet.",
    "ogImage": "https://images.unsplash.com/photo-1470004914212-05527e49370b?auto=format&fit=crop&w=900&q=80",
    "factCheckedBy": "Sarah Cadi",
    "sensitiveTopic": false,
    "heroImageAlt": "Transports : les retards se concentrent dans le nord de la ville",
    "imageCredit": "Photo: Unsplash",
    "location": "Marseille",
    "series": "ville-et-quartiers",
    "relatedArticles": [
      "arretes-municipaux-riverains",
      "cantines-prix-qualite-quartiers",
      "dockers-port-autonome"
    ],
    "sourceLinks": [],
    "authorId": "sarah-cadi",
    "factCheckedById": "sarah-cadi",
    "sections": [],
    "sources": [],
    "corrections": [],
    "redirectFrom": [],
    "dataHighlights": []
  },
  {
    "id": "mediterranee-argument-politique",
    "title": "La Méditerranée comme argument politique permanent",
    "excerpt": "Quand les élus invoquent l'exception marseillaise, que disent vraiment les arbitrages budgétaires ?",
    "caption": "Chronique signée rédaction Mistral.",
    "image": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80",
    "date": "2026-03-03",
    "updatedDate": "2026-03-05",
    "author": "Paul Ferrand",
    "readTimeMinutes": 5,
    "tags": [
      "Politique",
      "Culture"
    ],
    "editorialTemplate": "portrait",
    "status": "published",
    "publishAt": "2026-03-03T06:00:00.000Z",
    "seoTitle": "La Méditerranée comme argument politique permanent",
    "seoDescription": "Quand les élus invoquent l'exception marseillaise, que disent vraiment les arbitrages budgétaires ?",
    "ogImage": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80",
    "factCheckedBy": "Paul Ferrand",
    "sensitiveTopic": false,
    "heroImageAlt": "La Méditerranée comme argument politique permanent",
    "imageCredit": "Photo: Unsplash",
    "location": "Marseille",
    "series": "finances-publiques-marseille",
    "relatedArticles": [
      "arretes-municipaux-riverains",
      "cantines-prix-qualite-quartiers",
      "dockers-port-autonome"
    ],
    "sourceLinks": [],
    "authorId": "paul-ferrand",
    "factCheckedById": "paul-ferrand",
    "sections": [],
    "sources": [],
    "corrections": [],
    "redirectFrom": [],
    "dataHighlights": []
  },
  {
    "id": "ecoles-renovees-marches",
    "title": "Écoles rénovées : les marchés publics passés au crible",
    "excerpt": "Un relevé ligne par ligne des appels d'offres fait ressortir des écarts de coûts non expliqués.",
    "caption": "Documents consolidés sur douze établissements.",
    "image": "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=900&q=80",
    "date": "2026-02-26",
    "updatedDate": "2026-03-01",
    "author": "Amel Chabane",
    "readTimeMinutes": 9,
    "sources": [
      {
        "label": "Subventions associations Marseille 2024",
        "file": "subventions-associations-marseille-2024.csv",
        "type": "Jeu de données (CSV)",
        "date": "2026-02-27",
        "context": "Permet de contrôler les écarts entre montants votés et montants effectivement versés."
      }
    ],
    "tags": [
      "Urbanisme",
      "Économie"
    ],
    "editorialTemplate": "enquete",
    "status": "published",
    "publishAt": "2026-02-26T06:00:00.000Z",
    "seoTitle": "Écoles rénovées : les marchés publics passés au crible",
    "seoDescription": "Un relevé ligne par ligne des appels d'offres fait ressortir des écarts de coûts non expliqués.",
    "ogImage": "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=900&q=80",
    "factCheckedBy": "Amel Chabane",
    "legalReviewedBy": "Léa Martin",
    "sensitiveTopic": false,
    "heroImageAlt": "Écoles rénovées : les marchés publics passés au crible",
    "imageCredit": "Photo: Unsplash",
    "location": "Marseille",
    "series": "finances-publiques-marseille",
    "relatedArticles": [
      "arretes-municipaux-riverains",
      "cantines-prix-qualite-quartiers",
      "dockers-port-autonome"
    ],
    "sourceLinks": [],
    "authorId": "amel-chabane",
    "factCheckedById": "amel-chabane",
    "legalReviewedById": "lea-martin",
    "sections": [],
    "corrections": [],
    "redirectFrom": [],
    "dataHighlights": []
  },
  {
    "id": "arretes-municipaux-riverains",
    "title": "Les arrêtés municipaux réclamés par les riverains",
    "excerpt": "Mistral publie les textes complets pour suivre ce qui a réellement été décidé autour des grands chantiers.",
    "caption": "Téléchargements disponibles dans l'espace documents.",
    "image": "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=900&q=80",
    "date": "2026-02-21",
    "updatedDate": "2026-02-22",
    "author": "Léa Martin",
    "readTimeMinutes": 6,
    "sources": [
      {
        "label": "Arrêté municipal circulation Vieux-Port 2024",
        "file": "arrete-circulation-vieux-port-2024.txt",
        "type": "Arrêté municipal",
        "date": "2026-02-20",
        "context": "Texte de référence cité pour vérifier les décisions réellement applicables sur le terrain."
      }
    ],
    "tags": [
      "Urbanisme",
      "Politique"
    ],
    "editorialTemplate": "enquete",
    "status": "published",
    "publishAt": "2026-02-21T06:00:00.000Z",
    "seoTitle": "Les arrêtés municipaux réclamés par les riverains",
    "seoDescription": "Mistral publie les textes complets pour suivre ce qui a réellement été décidé autour des grands chantiers.",
    "ogImage": "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=900&q=80",
    "factCheckedBy": "Léa Martin",
    "legalReviewedBy": "Léa Martin",
    "sensitiveTopic": false,
    "heroImageAlt": "Les arrêtés municipaux réclamés par les riverains",
    "imageCredit": "Photo: Unsplash",
    "location": "Marseille",
    "series": "finances-publiques-marseille",
    "relatedArticles": [
      "cantines-prix-qualite-quartiers",
      "dockers-port-autonome",
      "ecoles-renovees-marches"
    ],
    "sourceLinks": [],
    "authorId": "lea-martin",
    "factCheckedById": "lea-martin",
    "legalReviewedById": "lea-martin",
    "sections": [],
    "corrections": [],
    "redirectFrom": [],
    "dataHighlights": []
  },
  {
    "id": "memoire-belle-de-mai",
    "title": "À la Belle de Mai, une mémoire de quartier s'organise",
    "excerpt": "Carnets, affiches et photos de façade composent une archive citoyenne face au récit officiel.",
    "caption": "Rencontre dans un ancien atelier partagé.",
    "image": "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=900&q=80",
    "date": "2026-02-16",
    "updatedDate": "2026-02-17",
    "author": "Yanis Gherbi",
    "readTimeMinutes": 5,
    "tags": [
      "Culture",
      "Quartiers"
    ],
    "editorialTemplate": "portrait",
    "status": "published",
    "publishAt": "2026-02-16T06:00:00.000Z",
    "seoTitle": "À la Belle de Mai, une mémoire de quartier s'organise",
    "seoDescription": "Carnets, affiches et photos de façade composent une archive citoyenne face au récit officiel.",
    "ogImage": "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=900&q=80",
    "factCheckedBy": "Yanis Gherbi",
    "sensitiveTopic": false,
    "heroImageAlt": "À la Belle de Mai, une mémoire de quartier s'organise",
    "imageCredit": "Photo: Unsplash",
    "location": "Marseille",
    "series": "ville-et-quartiers",
    "relatedArticles": [
      "arretes-municipaux-riverains",
      "cantines-prix-qualite-quartiers",
      "dockers-port-autonome"
    ],
    "sourceLinks": [],
    "authorId": "yanis-gherbi",
    "factCheckedById": "yanis-gherbi",
    "sections": [],
    "sources": [],
    "corrections": [],
    "redirectFrom": [],
    "dataHighlights": []
  },
  {
    "id": "tramway-est-hypotheses",
    "title": "Extension du tramway à l'est : les hypothèses sur la table",
    "excerpt": "Trois scénarios de tracé sont analysés avec leurs impacts budgétaires et leurs effets sur la desserte locale.",
    "caption": "Simulation à partir des dernières délibérations publiques.",
    "image": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=900&q=80",
    "date": "2026-02-11",
    "updatedDate": "2026-02-14",
    "author": "Sarah Cadi",
    "readTimeMinutes": 8,
    "tags": [
      "Mobilités",
      "Urbanisme",
      "Économie"
    ],
    "editorialTemplate": "enquete",
    "status": "published",
    "publishAt": "2026-02-11T06:00:00.000Z",
    "seoTitle": "Extension du tramway à l'est : les hypothèses sur la table",
    "seoDescription": "Trois scénarios de tracé sont analysés avec leurs impacts budgétaires et leurs effets sur la desserte locale.",
    "ogImage": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=900&q=80",
    "factCheckedBy": "Sarah Cadi",
    "sensitiveTopic": false,
    "heroImageAlt": "Extension du tramway à l'est : les hypothèses sur la table",
    "imageCredit": "Photo: Unsplash",
    "location": "Marseille",
    "series": "finances-publiques-marseille",
    "relatedArticles": [
      "arretes-municipaux-riverains",
      "cantines-prix-qualite-quartiers",
      "dockers-port-autonome"
    ],
    "sourceLinks": [],
    "authorId": "sarah-cadi",
    "factCheckedById": "sarah-cadi",
    "sections": [],
    "sources": [],
    "corrections": [],
    "redirectFrom": [],
    "dataHighlights": []
  },
  {
    "id": "friches-culturelles-sud",
    "title": "Friches culturelles du sud : qui décide des occupations ?",
    "excerpt": "Derrière les projets temporaires, des arbitrages politiques tranchent entre programmation artistique et rentabilité.",
    "caption": "Entretiens croisés avec collectifs, mairie et exploitants.",
    "image": "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=900&q=80",
    "date": "2026-02-07",
    "updatedDate": "2026-02-10",
    "author": "Paul Ferrand",
    "readTimeMinutes": 7,
    "tags": [
      "Culture",
      "Politique",
      "Quartiers"
    ],
    "editorialTemplate": "portrait",
    "status": "published",
    "publishAt": "2026-02-07T06:00:00.000Z",
    "seoTitle": "Friches culturelles du sud : qui décide des occupations ?",
    "seoDescription": "Derrière les projets temporaires, des arbitrages politiques tranchent entre programmation artistique et rentabilité.",
    "ogImage": "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=900&q=80",
    "factCheckedBy": "Paul Ferrand",
    "sensitiveTopic": false,
    "heroImageAlt": "Friches culturelles du sud : qui décide des occupations ?",
    "imageCredit": "Photo: Unsplash",
    "location": "Marseille",
    "series": "finances-publiques-marseille",
    "relatedArticles": [
      "arretes-municipaux-riverains",
      "cantines-prix-qualite-quartiers",
      "dockers-port-autonome"
    ],
    "sourceLinks": [],
    "authorId": "paul-ferrand",
    "factCheckedById": "paul-ferrand",
    "sections": [],
    "sources": [],
    "corrections": [],
    "redirectFrom": [],
    "dataHighlights": []
  }
];
